CREATE TABLE Users (
    ID VARCHAR(50) PRIMARY KEY,
    CREATED_DATE DATETIME,
    BIRTH_DATE DATE,
    STATE VARCHAR(5),
    LANGUAGE VARCHAR(10),
    GENDER VARCHAR(10)
)
LOAD DATA INFILE 'USER_TAKEHOME.csv'
INTO TABLE users
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(ID, CREATED_DATE, BIRTH_DATE, STATE, LANGUAGE, GENDER);

CREATE TABLE Transactions (
    RECEIPT_ID VARCHAR(50) PRIMARY KEY,
    PURCHASE_DATE DATE,
    SCAN_DATE DATETIME,
    STORE_NAME VARCHAR(50),
    USER_ID VARCHAR(50),
    BARCODE VARCHAR(50),
    FINAL_QUANTITY DECIMAL(10, 2),
    FINAL_SALE DECIMAL(10, 2)
);
LOAD DATA INFILE 'TRANSACTION_TAKEHOME.csv'
INTO TABLE Transactions
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(RECEIPT_ID, PURCHASE_DATE, SCAN_DATE, STORE_NAME, USER_ID, BARCODE, FINAL_QUANTITY, FINAL_SALE);

CREATE TABLE Products (
    CATEGORY_1 VARCHAR(50),
    CATEGORY_2 VARCHAR(50),
    CATEGORY_3 VARCHAR(50),
    CATEGORY_4 VARCHAR(50),
    MANUFACTURER VARCHAR(100),
    BRAND VARCHAR(50),
    BARCODE VARCHAR(50) PRIMARY KEY
);
LOAD DATA INFILE 'PRODUCTS_TAKEHOME.csv'
INTO TABLE Products
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(CATEGORY_1, CATEGORY_2, CATEGORY_3, CATEGORY_4, MANUFACTURER, BRAND, BARCODE);